### ISSUE TITLE
Update nimble guide

### ISSUE THREAD

**Issue by whadar** [Peer5/peer5-docs#1]
@arikkrol1 please see the guide here

**Comment by whadar** [comment]
https://github.com/Peer5/mkdocs-base/blob/master/docs/Guides/HLS%20with%20Nimble.md

**Comment by shacharz** [comment]
https://docs.google.com/document/d/1Q4ix-FrBttfyXHkBSL1piuIyrKZZXdT9VheO-MERYuU/edit
