### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by whadar** [Peer5/peer5-docs#26]
Docs should run on https

![image](https://cloud.githubusercontent.com/assets/922633/15870856/7a6da090-2cfa-11e6-82d1-d39d7b843276.png)

**Comment by mrbar42** [comment]
Duplicate of #22

**Comment by whadar** [comment]
Let's get this done before the rest of the related issues, since it's quick and important

**Comment by shaharmor** [comment]
Done.
@whadar should this be https only?

**Comment by shaharmor** [comment]
Made https-only
