### ISSUE TITLE
reformat Flash migration guide a bit

### ISSUE THREAD

**Issue by huancle** [Peer5/peer5-docs#50]
Under the "VideoJS5 Configuration" section, the two plugins that we mention:

- https://github.com/Peer5/videojs-contrib-hls.js 
- https://github.com/videojs/videojs-contrib-hls

should be listed on individual lines and should be links instead of just text.

Hadar also wants to explain the difference between the two plugins. Or we should just list one. Less choice = better !!

**Comment by mrbar42** [comment]
What do you mean by "individual lines"?
They are on two lines and they are already links

**Comment by shacharz** [comment]
@mrbar42 They're not, take a look how it looks on https://docs.peer5.com/guides/migrate-from-flash/
