### ISSUE TITLE
add instructions for CommonJS hls.js usage

### ISSUE THREAD

**Issue by mrbar42** [Peer5/peer5-docs#99]
add instructions for CommonJS hls.js usage

either by exposing Hls to the global
```js
var Hls = window.Hls = require('hls.js');
```

or passing loader in the config
```js
var Hls = require('hls.js');
var instance = new Hls({load: peer5.HlsJsLoader});
```

**Comment by benjamingr** [comment]
We might probably want to show an `import/export` example while we're at it (I suspect it's more common, and it's what r7 which we raised this issue for use).

**Comment by whadar** [comment]
@mrbar42 @shacharz Requested by R7, Switch Media and a few others. Can we invest an hour with a full example and update so they can use it?
